include $(TOPDIR)/rules.mk

LUCI_TITLE:=SD-WRT path intelligence dashboard (LuCI)
LUCI_DEPENDS:=+luci-base +sd-wrt +rpcd
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=mike.foxworthy@gmail.com

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
